#!/bin/bash
#SBATCH -J post_BL
#SBATCH -o post_BL.%j.out
#SBATCH -e post_BL.%j.err
#SBATCH -A scalo
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --exclusive
#SBATCH -t 24:00:00

export bin_path="/scratch/bell/vpulleti/winglet_data/binary/BL_w0_2D/"
export ascii_path="/scratch/bell/vpulleti/winglet_data/BL_w0_2D/"
export plot_path="/scratch/bell/vpulleti/winglet_data/plots/BL_w0_2D/"
export prefix="BL_w0_2D"
export bin_name="/scratch/bell/vpulleti/winglet_data/binary/BL_w0_2D/BL_w0_2D_"

python3 -u POD_winglets_BL_entrainment.py $bin_path $ascii_path $plot_path $prefix $bin_name

export bin_path="/scratch/bell/vpulleti/winglet_data/binary/BL_w1_2D/"
export ascii_path="/scratch/bell/vpulleti/winglet_data/BL_w1_2D/"
export plot_path="/scratch/bell/vpulleti/winglet_data/plots/BL_w1_2D/"
export prefix="BL_w1_2D"
export bin_name="/scratch/bell/vpulleti/winglet_data/binary/BL_w1_2D/BL_w1_2D_"

python3 -u POD_winglets_BL_entrainment.py $bin_path $ascii_path $plot_path $prefix $bin_name


export bin_path="/scratch/bell/vpulleti/winglet_data/binary/BL_w2_2D/"
export ascii_path="/scratch/bell/vpulleti/winglet_data/BL_w2_2D/"
export plot_path="/scratch/bell/vpulleti/winglet_data/plots/BL_w2_2D/"
export prefix="BL_w2_2D"
export bin_name="/scratch/bell/vpulleti/winglet_data/binary/BL_w2_2D/BL_w2_2D_"

python3 -u POD_winglets_BL_entrainment.py $bin_path $ascii_path $plot_path $prefix $bin_name


export bin_path="/scratch/bell/vpulleti/winglet_data/binary/BL_w3_2D/"
export ascii_path="/scratch/bell/vpulleti/winglet_data/BL_w3_2D/"
export plot_path="/scratch/bell/vpulleti/winglet_data/plots/BL_w3_2D/"
export prefix="BL_w3_2D"
export bin_name="/scratch/bell/vpulleti/winglet_data/binary/BL_w3_2D/BL_w3_2D_"

python3 -u POD_winglets_BL_entrainment.py $bin_path $ascii_path $plot_path $prefix $bin_name


export bin_path="/scratch/bell/vpulleti/winglet_data/binary/BL_w0_7D/"
export ascii_path="/scratch/bell/vpulleti/winglet_data/BL_w0_7D/"
export plot_path="/scratch/bell/vpulleti/winglet_data/plots/BL_w0_7D/"
export prefix="BL_w0_7D"
export bin_name="/scratch/bell/vpulleti/winglet_data/binary/BL_w0_7D/BL_w0_7D_"

python3 -u POD_winglets_BL_entrainment.py $bin_path $ascii_path $plot_path $prefix $bin_name

export bin_path="/scratch/bell/vpulleti/winglet_data/binary/BL_w1_7D/"
export ascii_path="/scratch/bell/vpulleti/winglet_data/BL_w1_7D/"
export plot_path="/scratch/bell/vpulleti/winglet_data/plots/BL_w1_7D/"
export prefix="BL_w1_7D"
export bin_name="/scratch/bell/vpulleti/winglet_data/binary/BL_w1_7D/BL_w1_7D_"

python3 -u POD_winglets_BL_entrainment.py $bin_path $ascii_path $plot_path $prefix $bin_name


export bin_path="/scratch/bell/vpulleti/winglet_data/binary/BL_w2_7D/"
export ascii_path="/scratch/bell/vpulleti/winglet_data/BL_w2_7D/"
export plot_path="/scratch/bell/vpulleti/winglet_data/plots/BL_w2_7D/"
export prefix="BL_w2_7D"
export bin_name="/scratch/bell/vpulleti/winglet_data/binary/BL_w2_7D/BL_w2_7D_"

python3 -u POD_winglets_BL_entrainment.py $bin_path $ascii_path $plot_path $prefix $bin_name


export bin_path="/scratch/bell/vpulleti/winglet_data/binary/BL_w3_7D/"
export ascii_path="/scratch/bell/vpulleti/winglet_data/BL_w3_7D/"
export plot_path="/scratch/bell/vpulleti/winglet_data/plots/BL_w3_7D/"
export prefix="BL_w3_7D"
export bin_name="/scratch/bell/vpulleti/winglet_data/binary/BL_w3_7D/BL_w3_7D_"

python3 -u POD_winglets_BL_entrainment.py $bin_path $ascii_path $plot_path $prefix $bin_name
